services:
  file-server:
    image: nginx:1.27-alpine
    profiles:
      - local-test-nginx
    ports:
      - "8081:80"
    volumes:
      - ${OUTPUT_DIR:-../data}:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
